#!/usr/bin/env python3
"""Generate src/inline_ignores/unicode_tables.rs from the Unicode Character Database.

The sanitizer (src/inline_ignores/sanitize.rs) keeps text through an allow-list, so it needs to
know exactly which code points are assigned, visible and not default-ignorable. Block ranges are
not good enough: blocks contain unassigned holes, and an unassigned code point is an invisible
carrier. This script emits explicit range tables instead.

Usage (the files are untrusted downloads: keep them in their own empty directory):

    mkdir /tmp/ucd18 && cd /tmp/ucd18
    for f in UnicodeData.txt DerivedCoreProperties.txt StandardizedVariants.txt; do
      curl -sSO https://www.unicode.org/Public/18.0.0/ucd/$f
    done
    python3 -I scripts/gen-unicode-tables.py /tmp/ucd18 18.0.0 > src/inline_ignores/unicode_tables.rs

A code point newer than the pinned version is not in any table, so it is dropped until the tables
are regenerated: the failure mode is safe (a new letter is lost, never an invisible kept).
"""

import re
import sys
from pathlib import Path

# Assigned characters that are general-category L/N/P/S yet render blank, so they would carry a
# payload. The visible-but-odd ones (U+2422 BLANK SYMBOL, the punctuation "gap fillers") stay.
BLANK_GRAPHICS = {
    0x2800,  # BRAILLE PATTERN BLANK
    0x303F,  # IDEOGRAPHIC HALF FILL SPACE
    0x13441,  # EGYPTIAN HIEROGLYPH FULL BLANK
    0x13442,  # EGYPTIAN HIEROGLYPH HALF BLANK
    0x1D159,  # MUSICAL SYMBOL NULL NOTEHEAD
    0xFFFC,  # OBJECT REPLACEMENT CHARACTER (a placeholder, not text)
}


def parse_unicode_data(path):
    """Yields (code point, general category) for every assigned code point."""
    first = None
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        cp, name, gc = int(fields[0], 16), fields[1], fields[2]
        if name.endswith(", First>"):
            first = cp
        elif name.endswith(", Last>"):
            for c in range(first, cp + 1):
                yield c, gc
            first = None
        else:
            yield cp, gc


def merge(points):
    """Sorted code points -> inclusive (lo, hi) ranges."""
    ranges = []
    for cp in sorted(points):
        if ranges and ranges[-1][1] + 1 == cp:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return [(lo, hi) for lo, hi in ranges]


def default_ignorable(path):
    points = set()
    in_section = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# Derived Property: Default_Ignorable_Code_Point"):
            in_section = True
            continue
        if in_section and line.startswith("# Total code points"):
            break
        match = re.match(r"([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*Default_Ignorable_Code_Point", line)
        if in_section and match:
            lo = int(match.group(1), 16)
            hi = int(match.group(2) or match.group(1), 16)
            points.update(range(lo, hi + 1))
    return points


def standardized_variants(path):
    """(base, selector) pairs with a selector in FE00..FE0D whose base is not a CJK ideograph.

    FE0E/FE0F (text/emoji presentation) and CJK ideographs are handled by rule in sanitize.rs.
    """
    pairs = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"([0-9A-F]+) ([0-9A-F]+);", line)
        if not match:
            continue
        base, selector = int(match.group(1), 16), int(match.group(2), 16)
        cjk = (
            0x2E80 <= base <= 0x2FDF
            or 0x3400 <= base <= 0x4DBF
            or 0x4E00 <= base <= 0x9FFF
            or 0xF900 <= base <= 0xFAFF
            or 0x20000 <= base <= 0x3FFFF
        )
        if 0xFE00 <= selector <= 0xFE0D and not cjk:
            pairs.append((base, selector))
    return sorted(pairs)


def emit_ranges(name, doc, ranges):
    print(f"/// {doc}")
    print(f"pub(super) const {name}: &[(u32, u32)] = &[")
    for lo, hi in ranges:
        print(f"    (0x{lo:X}, 0x{hi:X}),")
    print("];\n")


def main():
    ucd, version = Path(sys.argv[1]), sys.argv[2]
    graphic, mark = set(), set()
    for cp, gc in parse_unicode_data(ucd / "UnicodeData.txt"):
        if gc[0] in "LNPS" and cp not in BLANK_GRAPHICS:
            graphic.add(cp)
        elif gc in ("Mn", "Mc", "Me"):
            mark.add(cp)
    ignorable = default_ignorable(ucd / "DerivedCoreProperties.txt")
    graphic -= ignorable
    mark -= ignorable
    variants = standardized_variants(ucd / "StandardizedVariants.txt")

    print("// @generated by scripts/gen-unicode-tables.py; do not edit by hand.")
    print(f"// Source: Unicode Character Database {version} (UnicodeData.txt,")
    print("// DerivedCoreProperties.txt, StandardizedVariants.txt).\n")
    print("#[cfg_attr(not(test), allow(dead_code))]")
    print(f'pub(super) const UNICODE_VERSION: &str = "{version}";\n')
    emit_ranges(
        "GRAPHIC",
        "Assigned letters, numbers, punctuation and symbols (categories L*, N*, P*, S*) that are\n"
        "/// neither Default_Ignorable nor blank.",
        merge(graphic),
    )
    emit_ranges(
        "MARK",
        "Assigned combining marks (Mn, Mc, Me) that are not Default_Ignorable.",
        merge(mark),
    )
    emit_ranges("DEFAULT_IGNORABLE", "Default_Ignorable_Code_Point, assigned or reserved.", merge(ignorable))
    print("/// Standardized variation sequences (base, selector in FE00..FE0D) on non-CJK bases.")
    print("pub(super) const STANDARDIZED_VARIANTS: &[(u32, u32)] = &[")
    for base, selector in variants:
        print(f"    (0x{base:X}, 0x{selector:X}),")
    print("];")


main()
