use super::*;

fn check_source(src: &str) -> Result<Vec<Finding>> {
    crate::test_support::check_go_source(&ErrorContextChecker, src)
}

const WRAPPING_CONVENTION: &str =
    "func wrap(err error) error {\n\treturn fmt.Errorf(\"wrap: %w\", err)\n}\n";

#[test]
fn flags_bare_passthrough_when_wrapping_convention_exists() {
    let src = format!(
        "package main\nimport \"fmt\"\n{WRAPPING_CONVENTION}func g() error {{\n\terr := doThing()\n\tif err != nil {{\n\t\treturn err\n\t}}\n\treturn nil\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert_eq!(findings.len(), 1);
}

#[test]
fn does_not_flag_when_no_wrapping_convention_in_file() {
    let src = "package main\nfunc g() error {\n\terr := doThing()\n\tif err != nil {\n\t\treturn err\n\t}\n\treturn nil\n}\n";
    let findings = check_source(src).unwrap();
    assert!(findings.is_empty());
}

#[test]
fn does_not_flag_sentinel_comparison() {
    let src = format!(
        "package main\nimport (\n\t\"fmt\"\n\t\"io\"\n)\n{WRAPPING_CONVENTION}func g() error {{\n\terr := doThing()\n\tif err == io.EOF {{\n\t\treturn err\n\t}}\n\treturn nil\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert!(findings.is_empty());
}

#[test]
fn does_not_flag_errors_is_chain() {
    let src = format!(
        "package main\nimport (\n\t\"errors\"\n\t\"fmt\"\n)\n{WRAPPING_CONVENTION}func g() error {{\n\terr := doThing()\n\tif errors.Is(err, ErrNotFound) {{\n\t\treturn err\n\t}}\n\treturn nil\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert!(findings.is_empty());
}

#[test]
fn does_not_flag_defer_based_handling() {
    let src = format!(
        "package main\nimport \"fmt\"\n{WRAPPING_CONVENTION}func g() (err error) {{\n\tdefer func() {{\n\t\tif err != nil {{\n\t\t\terr = fmt.Errorf(\"deferred: %w\", err)\n\t\t}}\n\t}}()\n\treturn doThing()\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert!(findings.is_empty());
}

#[test]
fn does_not_flag_named_return_bare_return() {
    let src = format!(
        "package main\nimport \"fmt\"\n{WRAPPING_CONVENTION}func g() (result int, err error) {{\n\terr = doThing()\n\tif err != nil {{\n\t\treturn\n\t}}\n\treturn\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert!(findings.is_empty());
}

#[test]
fn does_not_flag_wrapped_return() {
    let src = format!(
        "package main\nimport \"fmt\"\n{WRAPPING_CONVENTION}func g() error {{\n\terr := doThing()\n\tif err != nil {{\n\t\treturn fmt.Errorf(\"g: %w\", err)\n\t}}\n\treturn nil\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert!(findings.is_empty());
}

#[test]
fn empty_file_produces_no_findings() {
    let findings = check_source("package main\n").unwrap();
    assert!(findings.is_empty());
}

#[test]
fn detects_wrapping_convention_in_raw_string_literal() {
    let src = "package main\nimport \"fmt\"\nfunc wrap(err error) error {\n\treturn fmt.Errorf(`wrap: %w`, err)\n}\nfunc g() error {\n\terr := doThing()\n\tif err != nil {\n\t\treturn err\n\t}\n\treturn nil\n}\n";
    let findings = check_source(src).unwrap();
    assert_eq!(findings.len(), 1);
}

#[test]
fn flags_parenthesized_condition() {
    let src = format!(
        "package main\nimport \"fmt\"\n{WRAPPING_CONVENTION}func g() error {{\n\terr := doThing()\n\tif (err != nil) {{\n\t\treturn err\n\t}}\n\treturn nil\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert_eq!(findings.len(), 1);
}

#[test]
fn flags_multi_value_bare_passthrough() {
    let src = format!(
        "package main\nimport \"fmt\"\n{WRAPPING_CONVENTION}func g() (int, error) {{\n\terr := doThing()\n\tif err != nil {{\n\t\treturn 0, err\n\t}}\n\treturn 0, nil\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert_eq!(findings.len(), 1);
}

/// Regression for a false positive found backtesting `stapler-squad`'s
/// `session/ent/claudesession_query.go`: an ent-generated file's boilerplate `%w`
/// helper isn't evidence anyone chose a wrapping convention for the file.
#[test]
fn does_not_flag_generated_file() {
    let src = format!(
        "// Code generated by ent, DO NOT EDIT.\n\npackage main\nimport \"fmt\"\n{WRAPPING_CONVENTION}func g() error {{\n\terr := doThing()\n\tif err != nil {{\n\t\treturn err\n\t}}\n\treturn nil\n}}\n"
    );
    let findings = check_source(&src).unwrap();
    assert!(findings.is_empty());
}

/// Regression for a false positive found backtesting kubernetes/kubernetes'
/// vendored `vendor/golang.org/x/net/http2/transport.go`: one incidental `%w`
/// call lost among many bare passthroughs isn't a chosen convention. Not fixed
/// via a `vendor/`-path exclusion since `kibitzer run`'s normal walk already
/// skips `vendor/` via `check::SKIP_DIRS` — this covers direct `check native`
/// invocation, which bypasses that walk.
#[test]
fn does_not_flag_lone_wrap_among_many_bare_passthroughs() {
    let mut src = format!("package main\nimport \"fmt\"\n{WRAPPING_CONVENTION}");
    for i in 0..4 {
        src.push_str(&format!(
                "func g{i}() error {{\n\terr := doThing()\n\tif err != nil {{\n\t\treturn err\n\t}}\n\treturn nil\n}}\n"
            ));
    }
    let findings = check_source(&src).unwrap();
    assert!(findings.is_empty());
}

/// Two or more independent wrap sites are unlikely to be accidental, so a
/// straggler is still flagged even though bare passthroughs outnumber wraps.
#[test]
fn flags_genuine_inconsistency_with_multiple_wrap_sites() {
    let src = "package main\nimport \"fmt\"\n\
                    func wrap1(err error) error {\n\treturn fmt.Errorf(\"wrap1: %w\", err)\n}\n\
                    func wrap2(err error) error {\n\treturn fmt.Errorf(\"wrap2: %w\", err)\n}\n\
                    func g() error {\n\terr := doThing()\n\tif err != nil {\n\t\treturn err\n\t}\n\treturn nil\n}\n";
    let findings = check_source(src).unwrap();
    assert_eq!(findings.len(), 1);
}

/// `err` is wrapped inside an earlier `if` block (not the immediately preceding
/// statement — there's an intervening block boundary) before the bare
/// `if err != nil { return err }` a few lines down. This is the narrow,
/// same-function backward scan `wrapped_earlier_in_enclosing_function` covers —
/// deliberately does NOT close the two real corpus false positives this checker
/// still has open (`pkg/kubelet/cm/dra/manager.go`, `session/workspace_peers.go`),
/// both of which wrap behind a called closure/function, not a textual
/// reassignment visible in the same function body — see
/// docs/go-error-context-false-positives.md's `## Log`.
#[test]
fn does_not_flag_when_wrapped_earlier_in_the_same_function() {
    let src = "package main\nimport \"fmt\"\n\
                    func wrap1(err error) error {\n\treturn fmt.Errorf(\"wrap1: %w\", err)\n}\n\
                    func wrap2(err error) error {\n\treturn fmt.Errorf(\"wrap2: %w\", err)\n}\n\
                    func g() error {\n\
                    \terr := doThing()\n\
                    \tif err != nil {\n\
                    \t\terr = fmt.Errorf(\"context: %w\", err)\n\
                    \t}\n\
                    \tif err != nil {\n\
                    \t\treturn err\n\
                    \t}\n\
                    \treturn nil\n\
                    }\n";
    let findings = check_source(src).unwrap();
    assert!(findings.is_empty());
}

/// True-positive guard: a *different*, never-wrapped identifier in the same
/// function must still flag — the backward scan must not suppress every bare
/// passthrough in a function just because some other variable was wrapped.
#[test]
fn still_flags_a_different_unwrapped_identifier_in_the_same_function() {
    let src = "package main\nimport \"fmt\"\n\
                    func wrap1(err error) error {\n\treturn fmt.Errorf(\"wrap1: %w\", err)\n}\n\
                    func wrap2(err error) error {\n\treturn fmt.Errorf(\"wrap2: %w\", err)\n}\n\
                    func g() error {\n\
                    \terr := doThing()\n\
                    \tif err != nil {\n\
                    \t\terr = fmt.Errorf(\"context: %w\", err)\n\
                    \t}\n\
                    \tif err != nil {\n\
                    \t\treturn err\n\
                    \t}\n\
                    \terr2 := doOtherThing()\n\
                    \tif err2 != nil {\n\
                    \t\treturn err2\n\
                    \t}\n\
                    \treturn nil\n\
                    }\n";
    let findings = check_source(src).unwrap();
    assert_eq!(findings.len(), 1);
}
